package demo;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: Test 1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.blazedemo.com/");
    // 2 | setWindowSize | 1528x794 | 
    driver.manage().window().setSize(new Dimension(1528, 794));
    // 3 | click | name=fromPort | 
    driver.findElement(By.name("fromPort")).click();
    // 4 | select | name=fromPort | label=Boston
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Boston']")).click();
    }
    // 5 | click | css=form | 
    driver.findElement(By.cssSelector("form")).click();
    // 6 | click | name=toPort | 
    driver.findElement(By.name("toPort")).click();
    // 7 | select | name=toPort | label=New York
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'New York']")).click();
    }
    // 8 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    // 9 | click | css=tr:nth-child(1) > td:nth-child(4) | 
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(4)")).click();
    // 10 | assertElementPresent | css=tr:nth-child(1) > td:nth-child(4) | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(4)"));
      assert(elements.size() > 0);
    }
    // 11 | click | css=tr:nth-child(1) > td:nth-child(2) | 
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
    // 12 | click | css=tr:nth-child(1) .btn | 
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn")).click();
    // 13 | click | id=inputName | 
    driver.findElement(By.id("inputName")).click();
    // 14 | click | css=p:nth-child(7) | 
    driver.findElement(By.cssSelector("p:nth-child(7)")).click();
    // 15 | click | id=inputName | 
    driver.findElement(By.id("inputName")).click();
    // 16 | type | id=inputName | Alexandre Lima Gazur
    driver.findElement(By.id("inputName")).sendKeys("Alexandre Lima Gazur");
    // 17 | type | id=address | Travessa do CampoLinho Nº2, Aldeia de Carvalho, Alcafache, Mangualde
    driver.findElement(By.id("address")).sendKeys("Travessa do CampoLinho Nº2, Aldeia de Carvalho, Alcafache, Mangualde");
    // 18 | type | id=city | Mangualde
    driver.findElement(By.id("city")).sendKeys("Mangualde");
    // 19 | type | id=zipCode | 3530-020
    driver.findElement(By.id("zipCode")).sendKeys("3530-020");
    // 20 | click | id=state | 
    driver.findElement(By.id("state")).click();
    // 21 | type | id=state | blah blah
    driver.findElement(By.id("state")).sendKeys("blah blah");
    // 22 | click | id=creditCardNumber | 
    driver.findElement(By.id("creditCardNumber")).click();
    // 23 | click | css=.control-group:nth-child(8) > .controls | 
    driver.findElement(By.cssSelector(".control-group:nth-child(8) > .controls")).click();
    // 24 | click | id=creditCardNumber | 
    driver.findElement(By.id("creditCardNumber")).click();
    // 25 | type | id=creditCardNumber | 897654466
    driver.findElement(By.id("creditCardNumber")).sendKeys("897654466");
    // 26 | click | id=nameOnCard | 
    driver.findElement(By.id("nameOnCard")).click();
    // 27 | type | id=nameOnCard | alg
    driver.findElement(By.id("nameOnCard")).sendKeys("alg");
    // 28 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    // 29 | click | css=tr:nth-child(2) > td:nth-child(2) | 
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2)")).click();
    // 30 | assertElementPresent | css=tr:nth-child(2) > td:nth-child(2) | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(2) > td:nth-child(2)"));
      assert(elements.size() > 0);
    }
    // 31 | assertTitle | BlazeDemo Confirmation | 
    assertThat(driver.getTitle()).isEqualTo("BlazeDemo Confirmation");
  }
}
